language: node_js
node_js:
- '7'
- '6'
- '4'

jobs:
  include:
    - stage: npm release
      node_js: '7'
      deploy:
        provider: npm
        email: tobias.lundin@gmail.com
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: tolu/ISO8601-duration
          branch: master
